### PR TITLE
chore: add generated types

### PR DESCRIPTION
**Pull request by NabbeunNabi**
Resolves #484 

# What changed
This updates the types that were generated by the graphQL schema changed in the PR #485 

# Testing instructions
No tests included. Just need to see that the types were updated. You can generate locally and see if they match the changes in this PR.

### CODE REVIEW

**Review by Anissa3005 — APPROVED** [review]
LGTM ✨

**Review by ermish — CHANGES_REQUESTED** [review]
sat here and thought through this for a whole minute. I think we want to have a location for facility AND professional.
Even if we don't use the facility one  in the UI now, I think that data may be very helpful in the future. 
For now, we could always just save it in the facility based on the one sent in the professional

**Comment by ermish** [comment]
any update on this? @NabbeunNabi  @Anissa3005

**Comment by NabbeunNabi** [comment]
We already have a location for the facility @ermish . Do we have one for healthcare professionals cuz they could be at multiple locations?

**Comment by NabbeunNabi** [comment]
Actually I don't remember doing this. I thought this was already updated?

**Comment by Anissa3005** [comment]
@NabbeunNabi @ermish This PR can be closed since in my #443 PR I update the types since I had to add some types to the schema.  @ermish I will take note of you commend about adding location to professionals, and create an issue for it

**Pull request closed without merging**
