### PR TITLE
52 seed data

### PR DESCRIPTION
**Pull request by ann-kilzer**
Part of #52 

I'm writing the logic around loading some seed data into the database. 

## Regarding the CSV files
I'm sure there will be some comments and thoughts about the contents seed data I've added here. I'd ask that we move those comments to the Google Doc where I am aggregating this information: https://docs.google.com/spreadsheets/d/19hrPp5YvHlEEelpnjMDL6Oh5UwHnST3SoKIudX6zk-M/edit#gid=1175476498

I've also asked in the MVP slack channel if Russ and Aya can add their input regarding medical data. As for the spoken languages, I've reused some information we gathered for speakher.jp

## Regarding the logic changes

- had to add `ts-node` to get the seed function to build

## how to test

1. Get your DB working by running the migration:
```
yarn prisma migrate dev
```

This should automatically run the seed file

OR if you previously ran the migrations:
```
yarn prisma db seed
```

2. View the data by running the prisma explorer: `yarn prisma studio` or if you prefer low level: `psql findadoc`

(If you ever want to[ reset your dev environment for testing](https://www.prisma.io/docs/reference/api-reference/command-reference#migrate-reset) use `yarn prisma migrate reset` 💣 

a. In the prisma explorer you can navigate to http://localhost:5555/ then click on `SpokenLanguages`, which should open up a table of the data that you can interact with (disregard English in there twice, I must have run the seeding on a dirty db)

Prisma_Studio

### CODE REVIEW

**Comment by theyokohamalife** [comment]
@ann-kilzer Thank you for working on this! I'm going to try to give this a proper review tomorrow, but can the information in the Google Docs be moved to Notion?

**Comment by ann-kilzer** [comment]
Hi @theyokohamalife. So the reason the data is in Google sheets is I need a spreadsheet that can be easily exported to CSV, I don't think Notion tables do that.

I linked to the sheet from Notion so we can find it: https://www.notion.so/ourjapanlife/Seed-Data-f1d6571dffe24984ab580a12c2692b3f

**Comment by theyokohamalife** [comment]
I get the following error when I run `yarn prisma migrate dev`. Is there a step before this?

Screen Shot 2022-12-31 at 3 41 12 PM

**Comment by ann-kilzer** [comment]
@theyokohamalife It looks like you didn't run the earlier steps, especially step 2 involving the `.env` file. Can you check that again?

**Comment by theyokohamalife** [comment]
> @theyokohamalife It looks like you didn't run the earlier steps, especially step 2 involving the `.env` file. Can you check that again?

@ann-kilzer Where can I find the earlier steps? They aren't in this PR description.

**Comment by ann-kilzer** [comment]
Oh I meant the database setup in the Readme

**Review by theyokohamalife — APPROVED** [review]
Works great!

**Pull request merged**
